### ISSUE TITLE
error parsing multipart form ... i/o timeout

### ISSUE THREAD

**Issue by jensfriisnielsen** [cloudlena/s3manager#37] opened 2023-07-24 08:51 UTC
Thank you for this awesome light-weight user friendly webui. :)

I'm trying to upload to a bucket using s3manager. I can confirm that I can upload small files. When I attempt to upload a file of 1.4Gb I get the error.

Below is the logs from the container.

```

2023/07/24 08:31:54 GET	/buckets	529.695212ms
2023/07/24 08:31:54 GET	/static/js/jquery-3.6.0.min.js	3.571188ms
2023/07/24 08:31:54 GET	/static/css/material-fonts.css	4.534327ms
2023/07/24 08:31:54 GET	/static/css/materialize.min.css	4.665875ms
2023/07/24 08:31:54 GET	/static/js/materialize.min.js	9.776546ms
2023/07/24 08:31:55 GET	/static/css/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2	1.945775ms
2023/07/24 08:31:56 GET	/buckets/uploads	371.396447ms
2023/07/24 08:31:57 GET	/static/css/material-fonts.css	1.716284ms
2023/07/24 08:31:57 GET	/static/js/jquery-3.6.0.min.js	2.522539ms
2023/07/24 08:31:57 GET	/static/css/materialize.min.css	3.027266ms
2023/07/24 08:31:57 GET	/static/js/materialize.min.js	3.070578ms
2023/07/24 08:35:55 GET	/buckets/uploads/	57.839621ms
2023/07/24 08:35:55 GET	/static/css/materialize.min.css	1.48533ms
2023/07/24 08:35:55 GET	/static/css/material-fonts.css	113.423µs
2023/07/24 08:35:55 GET	/static/js/jquery-3.6.0.min.js	465.394µs
2023/07/24 08:35:55 GET	/static/js/materialize.min.js	15.216274ms
2023/07/24 08:35:58 GET	/buckets	3.015084ms
2023/07/24 08:35:58 GET	/static/css/material-fonts.css	108.604µs
2023/07/24 08:35:58 GET	/static/js/jquery-3.6.0.min.js	279.164µs
2023/07/24 08:35:58 GET	/static/css/materialize.min.css	233.249µs
2023/07/24 08:35:58 GET	/static/js/materialize.min.js	229.151µs
2023/07/24 08:35:59 GET	/buckets/uploads	3.821679ms
2023/07/24 08:35:59 GET	/static/css/material-fonts.css	102.171µs
2023/07/24 08:35:59 GET	/static/css/materialize.min.css	204.654µs
2023/07/24 08:35:59 GET	/static/js/jquery-3.6.0.min.js	217.96µs
2023/07/24 08:35:59 GET	/static/js/materialize.min.js	176.682µs
2023/07/24 08:36:01 GET	/buckets/uploads/	2.401802ms
2023/07/24 08:36:02 GET	/static/css/material-fonts.css	81.022µs
2023/07/24 08:36:02 GET	/static/js/jquery-3.6.0.min.js	162.475µs
2023/07/24 08:36:02 GET	/static/css/materialize.min.css	196.139µs
2023/07/24 08:36:02 GET	/static/js/materialize.min.js	420.229µs
2023/07/24 08:38:20 GET	/buckets/uploads/	54.228247ms
2023/07/24 08:38:20 GET	/static/css/material-fonts.css	173.797µs
2023/07/24 08:38:20 GET	/static/js/jquery-3.6.0.min.js	185.85µs
2023/07/24 08:38:20 GET	/static/css/materialize.min.css	556.916µs
2023/07/24 08:38:20 GET	/static/js/materialize.min.js	13.022241ms
2023/07/24 08:38:20 GET	/static/css/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2	234.681µs
2023/07/24 08:38:20 GET	/favicon.ico	23.614µs
2023/07/24 08:38:31 POST	/api/buckets/uploads/objects	5.020486351s
2023/07/24 08:38:31 error parsing multipart form: read tcp 172.25.0.7:8080->172.25.0.2:35326: i/o timeout
2023/07/24 08:38:31 GET	/buckets/uploads/	2.265115ms
2023/07/24 08:38:31 GET	/static/css/material-fonts.css	96.743µs
2023/07/24 08:38:31 GET	/static/css/materialize.min.css	264.217µs
2023/07/24 08:38:31 GET	/static/js/jquery-3.6.0.min.js	311.956µs
2023/07/24 08:38:31 GET	/static/js/materialize.min.js	198.183µs
2023/07/24 08:38:31 GET	/static/css/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2	218.702µs
2023/07/24 08:38:34 GET	/buckets/uploads/	2.41638ms
2023/07/24 08:38:34 GET	/static/css/material-fonts.css	147.477µs
2023/07/24 08:38:34 GET	/static/js/jquery-3.6.0.min.js	225.174µs
2023/07/24 08:38:34 GET	/static/css/materialize.min.css	516.801µs
2023/07/24 08:38:34 GET	/static/js/materialize.min.js	368.822µs
2023/07/24 08:38:34 GET	/static/css/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2	248.457µs
2023/07/24 08:41:32 POST	/api/buckets/uploads/objects	5.018585869s
2023/07/24 08:41:32 error parsing multipart form: read tcp 172.25.0.7:8080->172.25.0.2:32776: i/o timeout
2023/07/24 08:41:32 GET	/buckets/uploads/	25.159823ms
2023/07/24 08:41:33 GET	/static/css/materialize.min.css	202.68µs
2023/07/24 08:41:33 GET	/static/js/jquery-3.6.0.min.js	94.768µs
2023/07/24 08:41:33 GET	/static/css/material-fonts.css	279.826µs
2023/07/24 08:41:33 GET	/static/js/materialize.min.js	966.496µs
2023/07/24 08:41:33 GET	/static/css/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2	170.792µs
```

**Comment by vominhtri231** [comment] 2023-07-27 17:07
The issue is fixed in https://github.com/cloudlena/s3manager/pull/38

**Closed** 2023-07-28 23:17 UTC
